
export const STUDENTS_SUCCESS = 'STUDENTS_SUCESS';
export const STUDENT_SUCCESS = 'STUDENT_SUCESS';
export const STUDENT_UPDATE_SUCCESS = 'STUDENT_UPDATE_SUCESS';
export const STUDENTT_DELETE_SUCCESS = 'STUDENTT_DELETE_SUCESS';

export const REQUEST_STUDENTS = 'REQUEST_STUDENTS';
export const REQUEST_STUDENT = 'REQUEST_STUDENT';
export const REQUEST_ADD_STUDENT = 'REQUEST_ADD_STUDENT';
export const REQUEST_UPDATE_STUDENT = 'REQUEST_UPDATE_STUDENT';
export const REQUEST_DELETE_STUDENT = 'REQUEST_DELETE_STUDENT';
export const REQUEST_SEARCH_STUDENTS = 'REQUEST_SEARCH_STUDENTS';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';

export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';